### ISSUE TITLE
No resource, method, or local variable named `path'

### ISSUE THREAD

**Issue by KostiantynGontar** [chef-cookbooks/freebsd#7]
Hello, can you help me with error?
I've included you cookbook and met the error during the Execute phase:

Error executing action `create` on resource 'freebsd_port_options[php5]'       
NameError       
No resource, method, or local variable named `path' for `Chef::Provider::FreebsdPortOptions ""'       

During next step, trying to indicate an issue,  I've changed you defaullt recipe adding an example from you README without incuding any cookbooks:

freebsd_port_options "php5" do
   options "APACHE" => true
   action :create
end

And had the same error. So, I can suggest that this error is in this cookbook not in inclusion or syntax. 
Also, I see that you test only `portsnap` recipe. Can you cover `freebsd_port_options` resource?

**Comment by steakknife** [comment]
Encountered the same error.

Contents of `site-cookbooks/base/templates/shells_bash-static.erb`

```shell
# This file is auto-generated by 'make config'.
# Options for bash-static-4.3.33
_OPTIONS_READ=bash-static-4.3.33
_FILE_COMPLETE_OPTIONS_LIST=COLONBREAKSWORDS DOCS HELP IMPLICITCD IMPORTFUNCTIONS NLS SYSLOG
OPTIONS_FILE_UNSET+=COLONBREAKSWORDS
OPTIONS_FILE_UNSET+=DOCS
OPTIONS_FILE_SET+=HELP
OPTIONS_FILE_UNSET+=IMPLICITCD
OPTIONS_FILE_UNSET+=IMPORTFUNCTIONS
OPTIONS_FILE_SET+=NLS
OPTIONS_FILE_UNSET+=SYSLOG
```

Stack trace:

```text
[2015-01-18T13:46:05-08:00] INFO: Processing freebsd_port_options[bash-static] action create (base::default line 31)
[2015-01-18T13:46:05-08:00] DEBUG: providers for generic freebsd_port_options resource enabled on node include: []
[2015-01-18T13:46:05-08:00] DEBUG: providers that refused resource freebsd_port_options[bash-static] were: []
[2015-01-18T13:46:05-08:00] DEBUG: providers that support resource freebsd_port_options[bash-static] include: []
[2015-01-18T13:46:05-08:00] DEBUG: no providers supported the resource, falling back to enabled handlers
[2015-01-18T13:46:05-08:00] DEBUG: providers that survived replacement include: []
[2015-01-18T13:46:05-08:00] DEBUG: dynamic provider resolver FAILED to resolve a provider

================================================================================
Error executing action `create` on resource 'freebsd_port_options[bash-static]'
================================================================================

NameError
---------
No resource, method, or local variable named `path' for `Chef::Provider::FreebsdPortOptions ""'

Cookbook Trace:
---------------
/root/chef/berks-cookbooks/freebsd/providers/port_options.rb:113:in `port_path'
/root/chef/berks-cookbooks/freebsd/providers/port_options.rb:120:in `ports_makefile_options_variable_value'
/root/chef/berks-cookbooks/freebsd/providers/port_options.rb:73:in `load_default_options'
/root/chef/berks-cookbooks/freebsd/providers/port_options.rb:61:in `load_current_resource'

Resource Declaration:
---------------------
# In /root/chef/site-cookbooks/base/recipes/default.rb

 31:   freebsd_port_options 'bash-static' do
 32:     source 'shells_bash-static.erb'
 33:     action :create
 34:   end
 35:

Compiled Resource:
------------------
# Declared in /root/chef/site-cookbooks/base/recipes/default.rb:31:in `from_file'

freebsd_port_options("bash-static") do
  action [:create]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  full_path "/var/db/ports/bash-static/options"
  declared_type :freebsd_port_options
  cookbook_name :base
  recipe_name "default"
  source "shells_bash-static.erb"
end

[2015-01-18T13:46:07-08:00] INFO: Running queued delayed notifications before re-raising exception
[2015-01-18T13:46:07-08:00] DEBUG: Re-raising exception: NameError - freebsd_port_options[bash-static] (base::default line 31) had an error: NameError: No resource, method, or local variable named `path' for `Chef::Provider::FreebsdPortOptions ""'
/opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:49:in `rescue in method_missing'
  /opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:44:in `method_missing'
  /root/chef/berks-cookbooks/freebsd/providers/port_options.rb:113:in `port_path'
  /root/chef/berks-cookbooks/freebsd/providers/port_options.rb:120:in `ports_makefile_options_variable_value'
  /root/chef/berks-cookbooks/freebsd/providers/port_options.rb:73:in `load_default_options'
  /root/chef/berks-cookbooks/freebsd/providers/port_options.rb:61:in `load_current_resource'
  /opt/chef/embedded/apps/chef/lib/chef/provider.rb:128:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:315:in `converge'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:400:in `block in run'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `catch'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:245:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:224:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
  /usr/bin/chef-solo:40:in `load'
  /usr/bin/chef-solo:40:in `<main>'
[2015-01-18T13:46:07-08:00] ERROR: Running exception handlers
[2015-01-18T13:46:07-08:00] ERROR: Exception handlers complete
[2015-01-18T13:46:07-08:00] FATAL: Stacktrace dumped to /root/chef/.chef/solo/cache/chef-stacktrace.out
[2015-01-18T13:46:07-08:00] DEBUG: NameError: freebsd_port_options[bash-static] (base::default line 31) had an error: NameError: No resource, method, or local variable named `path' for `Chef::Provider::FreebsdPortOptions ""'
/opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:49:in `rescue in method_missing'
/opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:44:in `method_missing'
/root/chef/berks-cookbooks/freebsd/providers/port_options.rb:113:in `port_path'
/root/chef/berks-cookbooks/freebsd/providers/port_options.rb:120:in `ports_makefile_options_variable_value'
/root/chef/berks-cookbooks/freebsd/providers/port_options.rb:73:in `load_default_options'
/root/chef/berks-cookbooks/freebsd/providers/port_options.rb:61:in `load_current_resource'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:128:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:315:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:400:in `block in run'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:245:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:224:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:40:in `load'
/usr/bin/chef-solo:40:in `<main>'
[2015-01-18T13:46:07-08:00] ERROR: freebsd_port_options[bash-static] (base::default line 31) had an error: NameError: No resource, method, or local variable named `path' for `Chef::Provider::FreebsdPortOptions ""'
[2015-01-18T13:46:08-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by sekrett** [comment]
It is easy to fix: https://github.com/chef-cookbooks/freebsd/pull/25
Please accept.
